# ***线性代数基础***

## 1.1标量的创建及基本运算

In [2]:
import torch
x1 = torch.tensor(3.0)
x2 = torch.tensor(2.0)
print(x1 , x2)

tensor(3.) tensor(2.)


标量由只有一个元素的张量表示,在这里演示实例化两个标量并进行一些计算处理

In [3]:
print(x1 + x2 , x1 * x2 , x1 - x2 , x1 / x2)

tensor(5.) tensor(6.) tensor(1.) tensor(1.5000)


在这里我们如果定义两个标量是浮点型,那么同python一样,计算结果也均是浮点型

In [4]:
#对x1,x2的定义进行修改试试
x1 = torch.tensor(3)
x2 = torch.tensor(2)
print(x1 , x2)
print(x1 + x2 , x1 * x2 , x1 - x2 , x1 / x2)
x2 = torch.tensor(2.0)
print(x2 , x1 + x2 , x1 * x2 , x1 - x2 , x1 / x2)

tensor(3) tensor(2)
tensor(5) tensor(6) tensor(1) tensor(1.5000)
tensor(2.) tensor(5.) tensor(6.) tensor(1.) tensor(1.5000)


如果将x1,x2分别定义成整数3和2，那么无论是输出x1,x2还是进行计算后的结果，都为整数，**但值得注意的是，若执行的是除法运算，那么无论输入标量是否为整数，都将输出浮点数**，这样的做法主要是为了保证计算结果精度,并且若为整数与浮点数之间的计算，那么结果将输出浮点数

## 1.2向量的创建和使用

In [5]:
x3 = torch.arange(4)
print(x3 , x3[1])

tensor([0, 1, 2, 3]) tensor(1)


通常，我们创建一个一维张量表示向量，且可以通过下标来引用向量内的元素,这一点类似于python中的列表索引，**需要注意的是引用出的向量中的元素是一个标量**

In [6]:
print(len(x3))
print(x3.shape)

4
torch.Size([4])


对只有一个轴或只是一个数字数组的张量，可以通过len()或.shape来查看其长度

## 1.3矩阵的创建和使用

矩阵在代码中表示为具有两个轴的张量

In [7]:
#矩阵的创建
A1 = torch.tensor([[1 , 2 , 3] , [4 , 5 , 6] , [7 , 8 , 9]])
print(A1)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


对矩阵的创建可以仿照对向量的创建，但是注意矩阵是有两个轴的

In [8]:
B1 = A1.T
print(B1)
B1 == B1.T 

tensor([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])


tensor([[ True, False, False],
        [False,  True, False],
        [False, False,  True]])

.T可以对矩阵求转置，矩阵和矩阵之间的比较将对矩阵内每个对应位置上的元素进行比较并返回布尔值

In [9]:
#矩阵的变换
A2 = torch.arange(20).reshape(5 , 4)
print(A2)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])


.reshape()可以对矩阵进行变换，对矩阵内元素总数可充满格式的矩阵可使用reshape(a , b)变换为a行b列的矩阵

## 1.4张量

### 1.4.1张量的性质

我们在之前对于向量和矩阵的讨论中多次提到了一个词--张量，那么什么是张量呢？ 我个人的理解为：就像向量是标量的推广，矩阵是向量的推广一样，我们可以构建具有更多轴的数据结构。张量是描述具有任意数量轴的n维数组的通用方法。例如，向量是一阶张量，矩阵是二阶张量......

In [10]:
A3 = torch.arange(24).reshape(2 , 3 , 4)
print(A3)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])


同样的，我们可以通过reshape()来构建一个三阶张量

### 1.4.2张量的基本性质

In [ ]:
#张量的基本运算
A4 = torch.arange(20 , dtype = torch.float32).reshape(5 , 4)  #强制类型为float32，默认情况下为int64
print(A4)
A5 = A4.clone()
print("矩阵A4加A5为:\n" , A4 + A5)
print("矩阵A4乘A5为:\n" , A4 * A5)
a = 2
print("2乘矩阵A4为:\n" , 2 * A4)
print("矩阵A4与2的和为\n:" , 2 + A4)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])
矩阵A4加A5为:
 tensor([[ 0.,  2.,  4.,  6.],
        [ 8., 10., 12., 14.],
        [16., 18., 20., 22.],
        [24., 26., 28., 30.],
        [32., 34., 36., 38.]])
矩阵A4乘A5为:
 tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])
2乘矩阵A4为:
 tensor([[ 0.,  2.,  4.,  6.],
        [ 8., 10., 12., 14.],
        [16., 18., 20., 22.],
        [24., 26., 28., 30.],
        [32., 34., 36., 38.]])
矩阵A4与2的和为
: tensor([[ 2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9.],
        [10., 11., 12., 13.],
        [14., 15., 16., 17.],
        [18., 19., 20., 21.]])


这里演示了如何使用代码实现矩阵的加法和乘法，具体实现原理参考线性代数数学教程

In [40]:
print((2 + A4).shape)
print((2 + A4).shape)

torch.Size([5, 4])
torch.Size([5, 4])


并且我们可以看到，对矩阵加法和乘法之改变矩阵内的元素值，并不改变矩阵的格式

## 1.5降维

### 1.5.1求和降维法

In [44]:
A5 = torch.arange(4 , dtype = torch.float32)
print(A5)
print(A5.sum())
A6 = torch.arange(24 , dtype = torch.float32).reshape(2 , 3 , 4)
print(A6)
print(A6.sum())

tensor([0., 1., 2., 3.])
tensor(6.)
tensor([[[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]],

        [[12., 13., 14., 15.],
         [16., 17., 18., 19.],
         [20., 21., 22., 23.]]])
tensor(276.)


使用.sum()可以对张量进行求和，无论是几阶张量，都将降维成一个求和标量，但是使用求和符号sum只能使张量沿所有轴进行降维

### 1.5.2沿任意轴进行降维

In [53]:
print(A4)
print(A4.shape)
A4_sum_axis0 = A4.sum(axis = 0)
print("沿行向量(轴0)降维:\n" , A4_sum_axis0)
print(A4_sum_axis0.shape)
A4_sum_axis1 = A4.sum(axis = 1)
print("沿列向量(轴1)降维:\n" , A4_sum_axis1)
print(A4_sum_axis1.shape)
A4_sum_axis0_axis1 = A1.sum(axis = [0 , 1])
print("沿着行向量和列向量(0轴和1轴)降维：\n" , A4_sum_axis0_axis1)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])
torch.Size([5, 4])
沿行向量(轴0)降维:
 tensor([40., 45., 50., 55.])
torch.Size([4])
沿列向量(轴1)降维:
 tensor([ 6., 22., 38., 54., 70.])
torch.Size([5])
沿着行向量和列向量(0轴和1轴)降维：
 tensor(45)


在通过求和符号进行实际降维的过程中可以通过axis进行指定沿何轴进行求和，对于二阶张量即矩阵，0轴对应行，1轴对应列,使用axis指定所有轴相当于直接使用sum求和符号进行降维

## 1.6非降维求和

对于降维求和，会减少张量的轴数，但是有时保留轴数也是必要的

In [6]:
import torch
A4 = torch.arange(20 , dtype = torch.float32).reshape(5 , 4) 
print(A4)
sum_A4 = A4.sum(axis = 1 ,keepdims = True)  #keepdims = True即保留该轴的指令
print(sum_A4)
print(A4 / sum_A4)
print(A4.cumsum(axis = 0))

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])
tensor([[ 6.],
        [22.],
        [38.],
        [54.],
        [70.]])
tensor([[0.0000, 0.1667, 0.3333, 0.5000],
        [0.1818, 0.2273, 0.2727, 0.3182],
        [0.2105, 0.2368, 0.2632, 0.2895],
        [0.2222, 0.2407, 0.2593, 0.2778],
        [0.2286, 0.2429, 0.2571, 0.2714]])
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  6.,  8., 10.],
        [12., 15., 18., 21.],
        [24., 28., 32., 36.],
        [40., 45., 50., 55.]])


要想保留轴即使用keepdims = True指令，默认情况下keepdims = False，即降维求和。
对于非降维求和的重要作用主要体现在：想用每行的总和去除以该行的每个元素（即归一化），如果不保持维度，形状会不匹配；而保持维度后，A / sum_A 会利用广播机制自动对齐，计算简洁且正确。
或者使用cumsum函数，这个函数可以保证沿着张量的某个轴计算该张量的累积总和但不会沿着任何轴降低张量的维度，比如在cumsum内使用axis = 0，即按行计算

## 1.7点积

In [10]:
A7 = torch.ones(4 , dtype = torch.float32)
A8 = torch.arange(4.0)
print(A7 , A8)
print(torch.dot(A7 , A8))
print(torch.sum(A7 * A8))

tensor([1., 1., 1., 1.]) tensor([0., 1., 2., 3.])
tensor(6.)
tensor(6.)


点积是两个矩阵相同位置元素的按元素乘积的和,并且，我们可以通过执行按照元素乘法，然后进行求和来表示向量的点积

## 1.8向量积与矩阵乘法

In [15]:
A8 = torch.arange(4.0 , dtype = torch.float32)
A7 = A7.reshape(1 , 4)
print(A7.shape , A8.shape)
print(torch.mv(A7 , A8))

torch.Size([1, 4]) torch.Size([4])
tensor([6.])


在代码中使用张量表示矩阵‐向量积，我们使用mv函数。当我们为矩阵A和向量x调用torch.mv(A7, A8)时，会执
行矩阵‐向量积。注意，A7的列维数（沿轴1的长度）必须与A8的维数（其长度）相同。

In [16]:
A9 = torch.arange(12).reshape(3 , 4)
A10 = torch.arange(16).reshape(4 , 4)
print(torch.mm(A9 , A10))

tensor([[ 56,  62,  68,  74],
        [152, 174, 196, 218],
        [248, 286, 324, 362]])


在代码中实现了矩阵乘法，需要注意的是在进行矩阵乘法操作时，需要保证前一个矩阵的列数等于后一个矩阵的行数，即A9_axis1 == A10_axis0